INSERT INTO lab.laboratory (lab_code, lab_name, district_id, lab_type_id)
SELECT v.lab_code, v.lab_name, d.id,
       (SELECT id FROM lab.lab_type WHERE name = 'disa')
FROM (VALUES
    ('ZBP', 'Kabwe General Hospital', 'Central', 'Kabwe'),
    ('ZKW', 'Kawama Health Post', 'Central', 'Kabwe'),
    ('ZMJ', 'Mwanjuni Health Laboratory', 'Central', 'Chibombo'),
    ('ZSJ', 'Serenje District Hospital', 'Central', 'Serenje'),
    ('MNC', 'Northen Command Military', 'Copperbelt', 'Ndola'),
    ('ZAP', 'Arthur Davison Children`s Hospital', 'Copperbelt', 'Ndola'),
    ('ZKT', 'Kitwe Central Hospital', 'Copperbelt', 'Kitwe'),
    ('ZLL', 'Lulamba clinic', 'Copperbelt', 'Chingola'),
    ('ZMH', 'Mutaba Health Post', 'Copperbelt', 'Masaiti'),
    ('ZNG', 'Peter Singogo Clinic', 'Copperbelt', 'Ndola'),
    ('ZNN', 'Nchanga North General Hospital', 'Copperbelt', 'Chingola'),
    ('ZNP', 'Ndola Teaching Hospital', 'Copperbelt', 'Ndola'),
    ('ZPC', 'Kitwe Police Camp', 'Copperbelt', 'Kitwe'),
    ('ZTT', 'Tropical Diseases Research Cen', 'Copperbelt', 'Ndola'),
    ('ZHW', 'Chimwemwe Level 1 Hospital', 'Copperbelt', 'Kitwe'),
    ('ZCF', 'Chifubu Level 1 Hospital', 'Copperbelt', 'Ndola'),
    ('ZWM', 'Malcom Watson Mine Hospital', 'Copperbelt', 'Mufulira'),
    ('ZWK', 'Wusakile Mine Hospital', 'Copperbelt', 'Kitwe'),
    ('ZCP', 'Chipata Central Hospital', 'Eastern', 'Chipata'),
    ('ZFM', 'St Francis Mission Hospital La', 'Eastern', 'Katete'),
    ('ZKP', 'Kapata Laboratory', 'Eastern', 'Chipata'),
    ('ZMG', 'Minga Mission Hospital', 'Eastern', 'Petauke'),
    ('ZMW', 'Mwami Mission Hopsital', 'Eastern', 'Chipata'),
    ('ZNY', 'Nyimba District Hopsital', 'Eastern', 'Nyimba'),
    ('ZPD', 'Petauke District Hospital', 'Eastern', 'Petauke'),
    ('ZLE', 'Lumezi Mission Hospital', 'Eastern', 'Lumezi'),
    ('ZCQ', 'Chipata District Hospital', 'Eastern', 'Chipata'),
    ('ZDK', 'Kamoto Mission Hospital', 'Eastern', 'Mambwe'),
    ('ZDZ', 'Chadiza District Hospital', 'Eastern', 'Chadiza'),
    ('ZEK', 'Kalindawalo General Hospital', 'Eastern', 'Petauke'),
    ('ZML', 'Mansa General Hospital', 'Luapula', 'Mansa'),
    ('ZMM', 'Musumali Health Post', 'Luapula', 'Mansa'),
    ('ZAC', 'St Pauls Mission Hospital', 'Luapula', 'Nchelenge'),
    ('MAF', 'Zambia Air Force HQ Laboratory', 'Lusaka', 'Lusaka'),
    ('MZM', 'Maina Soko Military Hospital', 'Lusaka', 'Lusaka'),
    ('ZCH', 'CHAZ Complex Laboratory', 'Lusaka', 'Lusaka'),
    ('ZCW', 'Chawama General Hospital', 'Lusaka', 'Lusaka'),
    ('ZFP', 'Levy Mwanawasa Teaching Hospital', 'Lusaka', 'Lusaka'),
    ('ZGH', 'George Health Centre', 'Lusaka', 'Lusaka'),
    ('ZIA', 'Kenneth Kaunda International A', 'Lusaka', 'Lusaka'),
    ('ZKF', 'Kafue Hospital Laboratory', 'Lusaka', 'Kafue'),
    ('ZLU', 'Zambia National Public Health', 'Lusaka', 'Lusaka'),
    ('ZMR', 'Lusaka Molecular Research & Di', 'Lusaka', 'Lusaka'),
    ('ZMT', 'Matero Laboratory', 'Lusaka', 'Lusaka'),
    ('ZNT', 'Chest Diseases Laboratory', 'Lusaka', 'Lusaka'),
    ('ZUL', 'University Teaching Hospital', 'Lusaka', 'Lusaka'),
    ('ZAE', 'Mpanshya (St Luke) Mission Hospital', 'Lusaka', 'Rufunsa'),
    ('ZCZ', 'Chelstone Urban Health Center', 'Lusaka', 'Lusaka'),
    ('ZCR', 'Chongwe Rural Referral', 'Lusaka', 'Chongwe'),
    ('ZKN', 'Kanyama 1st Level Hospital', 'Lusaka', 'Lusaka'),
    ('ZCG', 'Chipata 1st Level Hospital', 'Lusaka', 'Lusaka'),
    ('ZAA', 'AIDS Health Care Foundation Chifundo', 'Lusaka', 'Lusaka'),
    ('ZHH', 'National Heart Hospital', 'Lusaka', 'Chongwe'),
    ('ZCC', 'Chilenje 1st Level Hospital', 'Lusaka', 'Lusaka'),
    ('ZCN', 'Chinsali General Hospital', 'Muchinga', 'Chinsali'),
    ('ZAB', 'Chilonga Mission', 'Muchinga', 'Mpika'),
    ('ZCD', 'New Chinsali General Hospital', 'Muchinga', 'Chinsali'),
    ('ZKS', 'Kasama General Hospital', 'Northern', 'Kasama'),
    ('ZSP', 'Solwezi General Hospital', 'North-Western', 'Solwezi'),
    ('ZZC', 'Zambia Clinic', 'North-Western', 'Solwezi'),
    ('ZAL', 'Mukinge Mission Hospital', 'North-Western', 'Kasempa'),
    ('ZAM', 'Zambezi District', 'North-Western', 'Zambezi'),
    ('ZAK', 'Lumwana District Hospital', 'North-Western', 'Kalumbila'),
    ('ZAI', 'Mwinilunga District Hospital', 'North-Western', 'Mwinilunga'),
    ('ZAG', 'Solwezi Urban', 'North-Western', 'Solwezi'),
    ('ZCM', 'Choma General Hospital', 'Southern', 'Choma'),
    ('ZKD', 'Kalomo District Hospital', 'Southern', 'Kalomo'),
    ('ZKK', 'Chikankata Mission Hospital La', 'Southern', 'Chikankata'),
    ('ZLR', 'Livingstone General Hospital', 'Southern', 'Livingstone'),
    ('ZMB', 'Mazabuka General Hospital', 'Southern', 'Mazabuka'),
    ('ZMC', 'Mtendere Laboratory', 'Southern', 'Chirundu'),
    ('ZMN', 'Namwala Laboratory', 'Southern', 'Namwala'),
    ('ZOM', 'Monze Mission General Hospital', 'Southern', 'Monze'),
    ('ZZI', 'Zimba Mission Hospital', 'Southern', 'Zimba'),
    ('ZIT', 'Itezhi tezhi District Hospital', 'Southern', 'Itezhi-Tezhi'),
    ('ZCK', 'Chikuni Mission Hospital', 'Southern', 'Monze'),
    ('ZMO', 'Kaonga Mini Hospital', 'Southern', 'Mazabuka'),
    ('ZMS', 'Siavonga District Hospital', 'Southern', 'Siavonga'),
    ('ZMA', 'Maamba General Hospital', 'Southern', 'Sinazongwe'),
    ('ZRT', 'Macha Research Trust', 'Southern', 'Choma'),
    ('ZAH', 'Macha Mission Hospital', 'Southern', 'Choma'),
    ('ZKM', 'Kaoma Hospital', 'Western', 'Kaoma'),
    ('ZMP', 'Lewanika General Hospital', 'Western', 'Mongu'),
    ('ZSG', 'Senanga General Hospital', 'Western', 'Senanga'),
    ('ZWA', 'Mwandi Mission Hopsital', 'Western', 'Mwandi'),
    ('ZYD', 'Yeta District Hospital', 'Western', 'Sesheke'),
    ('ZMQ', 'Mongu Urban Clinic', 'Western', 'Mongu'),
    ('ZAD', 'Luampa Mission Hospital', 'Western', 'Luampa'),
    ('ZLK', 'Lukulu District Hospital', 'Western', 'Lukulu'),
    ('ZKB', 'Kalabo District Hospital', 'Western', 'Kalabo'),
    ('ZMU', 'Mongu District Hospital', 'Western', 'Mongu')
) AS v(lab_code, lab_name, province, district)
JOIN ref.province p ON p.name = v.province
JOIN ref.district d ON d.province_id = p.id AND d.name = v.district
ON CONFLICT (lab_code) DO NOTHING;
